# Label configuration for actions/labeler@v5
# https://github.com/actions/labeler

'area: app':
  - changed-files:
      - any-glob-to-any-file: 'app/**'

'area: components':
  - changed-files:
      - any-glob-to-any-file: 'components/**'

'area: lib':
  - changed-files:
      - any-glob-to-any-file: 'lib/**'

'area: tests':
  - changed-files:
      - any-glob-to-any-file: 'tests/**'

'area: database':
  - changed-files:
      - any-glob-to-any-file: 'drizzle/**'

'area: ci/cd':
  - changed-files:
      - any-glob-to-any-file: '.github/**'

'dependencies':
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - 'package-lock.json'

'documentation':
  - changed-files:
      - any-glob-to-any-file:
          - '*.md'
          - 'docs/**'
